# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
title: "嶽洋留記"
description: "一個歷史遊戲迷的回憶錄"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
remote_theme: uscache/mediumish-theme-jekyll
paginate: 6
paginate_path: "/page:num"

# header_pages:
#   - rey.md
  # - index.md
