# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
# remote_theme: jekyll-theme-minimal
title: My GitHub Page
description: Welcome to my site!
# theme: minima   # or cayman, slate, etc.
remote_theme: jekyll-theme-minimal
header_pages:
  - index.md
  - rey.md
